task_management/urls.py
from django.contrib import admin
from django.urls import include, path

from tasks import views

urlpatterns = [
    path('',include('tasks.urls')),
    path('tasks/', views.task_list, name='task_list'),
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls', namespace='tasks')),
]

tasks/urls.py
from django.urls import path
from . import views


app_name = 'tasks'
urlpatterns = [
    path('', views.menu, name='home'),
    path('<int:id>/', views.task_details, name='task_details'),
    path('<int:id>/status/', views.set_status, name='set_status'),
    path('filter/<int:status>/', views.filter_tasks, name='filter_tasks')
]

tasks/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Meta:
    ordering = ['-created_at']
    indexes = [models.Index(fields=['created_at'])]


def __str__(self):
    return self.title

tasks/views.py
from django.shortcuts import render
from tasks.models import Task
from django.http import Http404


def menu(request):
    return render(request, 'tasks/base.html')


def task_details(request, id):
    try:
        task = Task.objects.get(id=id)
    except Task.DoesNotExist:
        raise Http404
    return render(
        request,
        'tasks/task/details.html',
        {'task': task}
    )


def task_list(request):
    tasks = Task.objects.all()
    return render(
        request,
        'tasks/task/list.html',
        {'tasks': tasks}
    )


def set_status(request, id):
    task = Task.objects.get(id=id)
    task.is_completed = not task.is_completed
    task.save()

    return render(
        request,
        'tasks/task/details.html',
        {'task': task}
    )


def filter_tasks(request, status: int):
    is_completed = bool(status)
    tasks = Task.objects.filter(is_completed=is_completed)
    return render(
        request,
        'tasks/task/list.html',
        {'tasks': tasks}
    )

tasks/templates/tasks/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <style>

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f9;
            color: #333;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

        #content {
            width: 80%;
            max-width: 800px;
            background: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            margin: 20px;
        }


        h1 {
            font-size: 24px;
            color: #444;
            margin-bottom: 20px;
            text-align: center;
        }

        h2 {
            font-size: 20px;
            color: #555;
            margin: 15px 0;
        }


        a:hover {
            text-decoration: underline;
        }

        /* Date and Status */
        .date, .status {
            font-size: 14px;
            color: #888;
            margin: 5px 0;
        }

        .description {
            margin-top: 10px;
            font-size: 16px;
            line-height: 1.6;
        }

    </style>

</head>
<body>
<div id="content">
    {% block content %}
        <h1> Home Page </h1>

        <a href="{% url 'admin:index' %}">Admin</a>
        <br>
        <br>
        <a href="{% url 'task_list' %}">Tasks</a>
        <br>
        <br>
        <h2>Help</h2>
        <p style="font-size: 14px; color: #888; margin: 5px 0;">
            change status: id/status
            <br>
            filter by completed:
            filter/1
            <br>
            filter by not completed:
            filter/0
        </p>




    {% endblock %}
</div>

</body>
</html>

tasks/templates/tasks/task/details.html
{% extends 'tasks/base.html' %}
{% block title %}{{task.title }}{% endblock %}
{% block content %}
    <h1> {{ task.title }}</h1>
    {{task.description|linebreaks}}
        <p class="status">
        <br>
        {% if task.is_completed %}
            Completed
        {% else %}
            Not Completed
        {% endif %}
    </p>
    <p class="date">
        created at {{ task.created_at }}<br>
        last updated at {{ task.updated_at }}
    </p>



{% endblock %}

tasks/templates/tasks/task/list.html
{% extends 'tasks/base.html' %}
{%  block title %}Tasks{% endblock %}
{% block content %}
    <h1>The Tasks</h1>
    {% for task in tasks %}
    <h2>
        <a href="{% url 'tasks:task_details' task.id %}">
            {{ task.title }}
           </a>
    </h2>
        {{ task.description|truncatechars:30|linebreaks }}
        <br>
        {% if task.is_completed %}
            Completed
        {% else %}
            Not Completed
        {% endif %}

        <p class="date">
            created at {{ task.created_at }}
        </p>
    {% endfor %}
{% endblock %}